version: '3.8'
services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: sistema_escolar
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - db_data_preprod:/var/lib/mysql
    restart: unless-stopped

  app:
    build: .
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      DB_NAME: sistema_escolar
    depends_on:
      - db
    ports:
      - '8082:8080'
    restart: unless-stopped

volumes:
  db_data_preprod:
