version: '3.8'
services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: sistema_escolar
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    volumes:
      - db_data_homolog:/var/lib/mysql

  app:
    image: ${REGISTRY}/projetodevops:${IMAGE_TAG}
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: ${DB_ROOT_PASSWORD}
      DB_NAME: sistema_escolar
    ports:
      - '8080:8080'
    depends_on:
      - db

volumes:
  db_data_homolog:
