apiVersion: v1
kind: Service
metadata:
  name: school-scheduler
  namespace: school-scheduler-dev
  labels:
    app: school-scheduler
spec:
  selector:
    app: school-scheduler
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
