apiVersion: apps/v1
kind: Deployment
metadata:
  name: school-scheduler
spec:
  replicas: 2
  selector:
    matchLabels:
      app: school-scheduler
  template:
    metadata:
      labels:
        app: school-scheduler
    spec:
      containers:
        - name: school-scheduler
          image: PLACEHOLDER_REGISTRY/projetodevops:PLACEHOLDER_TAG
          env:
            - name: DB_HOST
              value: mysql
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: user
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: password
            - name: DB_NAME
              value: sistema_escolar
          ports:
            - containerPort: 8080
